// ──────────────────────────────────────────
// Export / Share utilities
// ──────────────────────────────────────────

/**
 * Export the matrix as a CSV file download.
 */
export function exportCSV(data) {
  const { options, criteria, scores, userInput } = data;

  const rows = [];

  // Header row
  rows.push(['Option', ...criteria.map((c) => `${c.name} (w:${c.weight}%)`), 'Weighted Total']);

  // Data rows
  options.forEach((opt) => {
    const total = criteria.reduce((sum, cr) => {
      const raw = parseFloat(scores[`${opt.id}_${cr.id}`]) || 0;
      return sum + (raw * cr.weight) / 100;
    }, 0);
    const cells = [
      opt.name,
      ...criteria.map((cr) => scores[`${opt.id}_${cr.id}`] ?? ''),
      total.toFixed(2),
    ];
    rows.push(cells);
  });

  // Metadata rows
  rows.push([]);
  rows.push(['Decision', userInput || '']);
  rows.push(['Generated by', 'Decision Matrix — AI-Powered Decision Making']);
  rows.push(['Date', new Date().toLocaleString()]);

  const csv = rows
    .map((r) => r.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(','))
    .join('\n');

  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' }); // BOM for Excel
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `decision-matrix-${Date.now()}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

/**
 * Encode matrix data into a URL-safe base64 string for sharing.
 * Uses TextEncoder instead of the deprecated escape/unescape.
 */
export function encodeShareURL(data) {
  try {
    const json = JSON.stringify(data);
    // TextEncoder → Uint8Array → base64
    const bytes = new TextEncoder().encode(json);
    let binary = '';
    bytes.forEach((b) => (binary += String.fromCharCode(b)));
    const encoded = btoa(binary)
      .replace(/\+/g, '-')  // URL-safe base64
      .replace(/\//g, '_')
      .replace(/=+$/, '');
    const url = `${window.location.origin}${window.location.pathname}?share=${encoded}`;
    return url;
  } catch {
    return null;
  }
}

/**
 * Decode shared matrix data from the URL query param.
 * Returns null if nothing to decode or decoding fails.
 */
export function decodeShareURL() {
  try {
    const params = new URLSearchParams(window.location.search);
    const encoded = params.get('share');
    if (!encoded) return null;

    // Restore standard base64 padding/chars
    const base64 = encoded
      .replace(/-/g, '+')
      .replace(/_/g, '/')
      .padEnd(encoded.length + ((4 - (encoded.length % 4)) % 4), '=');

    const binary = atob(base64);
    const bytes = Uint8Array.from(binary, (c) => c.charCodeAt(0));
    const json = new TextDecoder().decode(bytes);
    const parsed = JSON.parse(json);

    // Basic shape validation
    if (!parsed.options || !parsed.criteria || !parsed.scores) return null;
    return parsed;
  } catch {
    return null;
  }
}

/**
 * Copy text to clipboard — tries modern API first, then falls back to execCommand.
 * Returns true on success.
 */
export async function copyToClipboard(text) {
  if (navigator.clipboard && window.isSecureContext) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      // Fall through to legacy method
    }
  }
  // Legacy fallback
  try {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.cssText = 'position:fixed;top:0;left:0;opacity:0;pointer-events:none;';
    document.body.appendChild(ta);
    ta.focus();
    ta.select();
    const ok = document.execCommand('copy');
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}
